LYSApp/LYSApp.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LYSApp.Web.Utilities;
using LYSApp.Domain.SearchManagement;
using LYSApp.Model;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace LYSApp.Web.Controllers
{
    public class SearchController : Controller
    {
        
       private ISearchManagement searchManagement;

       public SearchController(SearchManagement searchManagement)
       {
           this.searchManagement = searchManagement;
       }

       // [HttpPost]
       // [ChildActionOnly]
       //public ActionResult Index()
       // {
       //     return View();
       // }

       public JsonResult GetArea(string term)
       {
           IList<SearchAreaViewModel> searchAreaList = searchManagement.GetAreas(term);
           string result = JsonConvert.SerializeObject(searchAreaList); 
           return Json(result, JsonRequestBehavior.AllowGet);

       }
        
       public ActionResult GetPGs(SearchViewModel searchViewModel)
       {
           if (searchViewModel !=null)
           {
               Session["SearchCriteria"] = searchViewModel;
               return View("Index", searchManagement.GetPGsBySearchCriteria(searchViewModel));
           }
           else
           {
               return RedirectToAction("Index", "Account");
           }
       }
      
      public ActionResult PropertyDetails(int PGID)
       {
           if (Session["SearchCriteria"] != null)
           {
               return View(searchManagement.GetPropertyDetails(PGID, Session["SearchCriteria"] as SearchViewModel));

           }
           else
           {
               return RedirectToAction("Index","Account");
           }
       }


      public ActionResult ReviewBooking(int RoomID)
      {
          BookingDetailsViewModel bookingDetailsViewModel = searchManagement.GetBookingDetails(RoomID);
          //BookingDetailsViewModel.User = LYSApp.Web.Services.SessionManager.GetSessionUser();
          return View(bookingDetailsViewModel);
      }
    }
}

LYSApp/LYSApp.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using LYSApp.Model;
using LYSApp.Domain.UserManagement;
using LYSApp.Domain;
using LYSApp.Web.Services;
using System.Threading.Tasks;
using Newtonsoft.Json;
using LYSApp.Web.Utilities;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;

namespace LYSApp.Web.Controllers
{
    [LYSUserAuthorize]
    public class UserController : Controller
    {
        private UserManager _userManager;
        private IUserManagement userManagement;
        UserViewModel userViewModel = new UserViewModel();
        public UserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<UserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        public UserController(UserManagement userManagement)
        {
            this.userManagement = userManagement;//Initializing UserManageManagement
        }

        // GET: User
        public async Task<ActionResult> ViewProfile()
        {

            var user = await UserManager.FindByIdAsync(SessionManager.GetSessionUser().Id);
            if (user != null)
            {
                userViewModel.ManageUserViewModel = new ManageUserViewModel();
                userViewModel.HouseReviewModel = new HouseReviewModel();
                userViewModel.UserID = user.Id;
                userViewModel.PhoneNumber = user.PhoneNumber;
                userViewModel.FirstName = user.FirstName;
                userViewModel.LastName = user.LastName;
                userViewModel.Gender = user.Gender;
                userViewModel.ProfilePicture = user.ProfilePicture;
                userViewModel.ManageUserViewModel.OldPassword = user.PasswordHash;
                userViewModel.Email = user.Email;
                userViewModel.EmailConfirmed = user.EmailConfirmed;
                userViewModel.PhoneNumber = user.PhoneNumber;
                userViewModel.PhoneNumberConfirmed = user.PhoneNumberConfirmed;
                userViewModel.UserName = user.UserName;
                userViewModel.HouseReviewModel.HouseID = userManagement.GetHouseID(user.Id);
                if (user.UserDetails != null && user.UserDetails.Count > 0)
                {
                    userViewModel.PresentAddress = user.UserDetails.FirstOrDefault().PresentAddress;
                    userViewModel.PermanentAddress = user.UserDetails.FirstOrDefault().PermanentAddress;
                    userViewModel.GovtIDType = user.UserDetails.FirstOrDefault().GovtIDType;
                    userViewModel.GovtID = user.UserDetails.FirstOrDefault().GovtID;
                    userViewModel.UserProfession = user.UserDetails.FirstOrDefault().UserProfession;
                    userViewModel.OfficeLocation = user.UserDetails.FirstOrDefault().OfficeLocation;
                    userViewModel.CurrentEmployer = user.UserDetails.FirstOrDefault().CurrentEmployer;
                    userViewModel.EmployeeID = user.UserDetails.FirstOrDefault().EmployeeID;
                    userViewModel.HighestEducation = user.UserDetails.FirstOrDefault().HighestEducation;
                    userViewModel.InstitutionName = user.UserDetails.FirstOrDefault().InstitutionName;
                }

                if (user.PGReviews != null && user.PGReviews.Count > 0){
                    userViewModel.pgReviews = user.PGReviews.ToList();
                }
            }
            return View(userViewModel);
        }

        [HttpPost]
        public ActionResult ViewProfile(UserViewModel userViewModel)
        {
            
            userViewModel.Status = 1;
            userViewModel.LastUpdatedOn = DateTime.Now;
           

            if (userViewModel.UserID == 0)
            {
                //UserController accountController = new UserController((UserManagement)userManagement);
                //accountController.Logout();

            }

            int count = userManagement.UpdateUser(userViewModel);
            if (count > 0)
            {
                var user = SessionManager.GetSessionUser();
                user.ProfilePicture = userViewModel.ProfilePicture;
                TempData["message"] = "Profile updated successfully!";
            }
            else
            {
                TempData["message"] = "Error in updating your profile.Please try again later";
                
            }
            return PartialView("_EditProfile", userViewModel);
        }


        [HttpPost]
        public virtual ActionResult CropImage(string imagePath, decimal? cropPointX, decimal? cropPointY, decimal? imageCropWidth, 
            decimal? imageCropHeight, string fileName)
        {
            if (string.IsNullOrEmpty(imagePath) || !cropPointX.HasValue || !cropPointY.HasValue || !imageCropWidth.HasValue || !imageCropHeight.HasValue)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            byte[] imageBytes = null;
            string[] imageUriPart = imagePath.Split(',');
            string base64String = imageUriPart[1];
            imageBytes = Convert.FromBase64String(base64String);
            byte[] croppedImage = ImageHelper.CropImage(imageBytes, (int)cropPointX.Value, (int)cropPointY.Value, (int)imageCropWidth.Value, (int)imageCropHeight.Value);

            if (!string.IsNullOrEmpty(fileName))
            {
                string[] getID = fileName.Split('_');
                string tempFolderName = Server.MapPath("~/files/croppedImages/" + getID[0]);
                DateTime timestamp = DateTime.Now;
                string filename = getID[0] + String.Format("{0:d-M-yyyy HH-mm-ss}", timestamp);
                FileHelper.SaveFile(croppedImage, tempFolderName, filename);

                string photoPath = string.Concat("../files/croppedImages/", "/" + getID[0], "/" + filename + ".png");
                
                int count = userManagement.UpdateProfilePicture(SessionManager.GetSessionUser().Id, photoPath);
                if (count > 0)
                {
                   
                    return Json(new { PhotoPath = photoPath, filename = filename + ".png" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
        }

        [HttpPost]
        public ActionResult AddComment(UserViewModel userViewModel)
        {
            userManagement.UpdateComment(userViewModel);
            return PartialView("_ReviewComments", userViewModel);
        }

    }
}

LYSApp/LYSApp.Web/Views/Shared/_EmailVerificationModal.cshtml
@model LYSApp.Model.EmailVerificationViewModel

<!-- Email Verification Modal -->
<div class="modal fade text-center" id="modalEmailVerification" role="dialog" aria-labelledby="emailverificationLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            @*<div class="modal-header">
                    <h4 class="modal-title" id="emailverificationLabel">Check your email</h4>
                </div>*@
            <div class="modal-body">
                @*<form role="form" id="form-EmailVerification">*@
                @using (Ajax.BeginForm("ResendAccountActivationMailForNewUser", new { ReturnUrl = ViewBag.ReturnUrl }, new AjaxOptions() { OnBegin = "resendemailverificationBegin", OnSuccess = "resendemailverificationSuccess", OnFailure = "resendemailverificationFailed", HttpMethod = "Post" }, new { role = "form", id = "form-ResendAccountActivationMailForNewUser", autocomplete = "off" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="errorblock form-group hidden">
                        <div class="alert alert-success modal-alert">
                            <div class="row no-margin">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                    <i class="fa fa-exclamation-circle"></i>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                                    <span class="errormessage"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h4>Check your email</h4>
                    <p>
                        Tap the link in the email we sent you.<br />
                        Confirming your email address helps us send you booking information.
                    </p>
                    <div class="circle-outer">
                        <div class="circle-inner">
                            <i class="fa fa-envelope-o"></i>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", maxlength = "50", placeholder = "Email", tabIndex = "1", @readonly = "readonly"})
                    </div>

                    <div class="form-group">
                        <div class="btn-group-justified">
                            <input type="submit" id="btnEmailVerification" class="btn btn-lg btn-green full-width" value="Resend Email" tabindex="2">
                        </div>
                    </div>
                }
                @*</form>*@
            </div>
        </div>
    </div>
</div> <!-- End Email Verification Modal -->

LYSApp/LYSApp.Web/Views/Shared/_ExternalLoginsListPartial.cshtml
@using LYSApp.Model
@model ExternalLoginListViewModel
@using Microsoft.Owin.Security


@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders!=null&& loginProviders.Count() > 0)
    {
        
        using (Html.BeginForm(Model.Action, "Account", new { ReturnUrl = Model.ReturnUrl }))
        {
            @Html.AntiForgeryToken()
            
                    foreach (AuthenticationDescription p in loginProviders)
                    {
                        if (p.AuthenticationType == "Facebook") { 
                        <div class="form-group">
                            <div class="btn-group-justified">
                                <button type="submit" class="btn btn-lg btn-facebook full-width" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account"><span class="fa fa-facebook pull-left"></span><span class="action">Sign Up</span> with Facebook</button>
                                <!-- based on the action class the inner text will be changed as Sign In or Sign Up  -->
                            </div>
                        </div>
                        }
                        else if (p.AuthenticationType == "Google")
                        {
                            <div class="form-group">
                                <div class="btn-group-justified">
                                    <button type="submit" class="btn btn-lg btn-google full-width" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account"><span class="fa fa-google-plus pull-left"></span><span class="action">Sign Up</span> with Google</button>
                                    <!-- based on the action class the inner text will be changed as Sign In or Sign Up  -->
                                </div>
                            </div>
                        }
                       
                    }
                    <div class="signOr">OR</div>
               
        }
    }
    
}

LYSApp/LYSApp.Web/Views/Shared/_Footer.cshtml
@using LYSApp.Web.Services.Common
<div class="home-footer">
    <div class="home-wrapper">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <div class="osLight footer-header">Company</div>
                <ul class="footer-nav pb20">
                    <li><a href="@Url.RouteUrl(RouteNames.AboutUs)">About</a></li>
                    <li><a href="@Url.RouteUrl(RouteNames.Jobs)">Jobs</a></li>
                    <li><a href="@Url.RouteUrl(RouteNames.ContactUs)">Contact</a></li>
                    <li><a href="@LYSConfig.BlogUrl" target="_blank">Blog</a></li>
                    <li><a href="@Url.RouteUrl(RouteNames.TermsAndPrivacy)">Terms & Privacy</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <div class="osLight footer-header">Discover</div>
                <ul class="footer-nav pb20">
                    <li><a href="@Url.RouteUrl(RouteNames.Jobs)">Become a Member</a></li>
                    <li><a data-toggle="modal" data-target="#modal-list-your-property">Properties List</a></li>
               </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <div class="osLight footer-header">Get in Touch</div>
                <ul class="footer-nav pb20">
                    <li class="footer-phone"><span class="fa fa-phone"></span> (+91)-9051979204</li>
                    <li class="footer-address osLight">
                        <p>Adinath Daffodils, PTC</p>
                        <p>Okkiyam Thuraipakkam, Chennai,</p>
                        <p>Tamil Nadu 600097</p>
                    </li>
                    <li>
                        <a href="@LYSConfig.FacebookUrl" target="_blank" class="btn btn-sm btn-icon btn-round btn-o btn-white"><span class="fa fa-facebook"></span></a> 
                        <a href="@LYSConfig.TwitterUrl" target="_blank" class="btn btn-sm btn-icon btn-round btn-o btn-white"><span class="fa fa-twitter"></span></a> 
                        <a href="@LYSConfig.GooglePlusUrl" target="_blank" class="btn btn-sm btn-icon btn-round btn-o btn-white"><span class="fa fa-google-plus"></span></a> 
                        <a href="@LYSConfig.LinkedinUrl" target="_blank" class="btn btn-sm btn-icon btn-round btn-o btn-white"><span class="fa fa-linkedin"></span></a> </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <div class="osLight footer-header">Subscribe to Our Newsletter</div>
                <form  role="form" id="form-Subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address" id="txtEmailForSubscribe" name="txtEmailForSubscribe" required>
                    </div>                    
                    <p id="subscribe-info" class="text-red"></p>                    
                    <div class="form-group">
                        <button type="button" class="btn btn-green btn-block btnSubscribe">Subscribe</button>
                    </div>
                </form>
                @*@using (Ajax.BeginForm("EmailSubscribe", "Account", FormMethod.Post, new AjaxOptions { UpdateTargetId = "subscribe-info" }))
                {
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address" name="txtEmailForSubscribe" required value="">
                    </div>
                    <p id="subscribe-info" class="text-red"></p>
                    <div class="form-group">
                        <button type="submit" class="btn btn-green btn-block btnSubscribe">Subscribe</button>
                    </div>
                }*@
            </div>
        </div>
        <div class="copyright">lockyourstay.com&copy; 2015-2016</div>
    </div>
</div>

LYSApp/LYSApp.Web/Views/Shared/_ForgotPasswordModal.cshtml
@model LYSApp.Model.ForgotPasswordViewModel 

<!-- Forgot Password Modal -->
<div class="modal fade" id="forgotpassword" role="dialog" aria-labelledby="forgotpasswordLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="forgotpasswordLabel">Forgot Password</h4>
            </div>
            <div class="modal-body">
                @*<form role="form" id="form-ForgotPassword">*@
                @using (Ajax.BeginForm("ForgotPassword", new { ReturnUrl = ViewBag.ReturnUrl }, new AjaxOptions() { OnBegin = "forgotpasswordBegin", OnSuccess = "forgotpasswordSuccess", OnFailure = "forgotpasswordFailed", HttpMethod = "Post" }, new { role = "form", id = "form-ForgotPassword", autocomplete = "off" }))
                {
                    @Html.AntiForgeryToken()                    
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", maxlength = "50", placeholder = "Email", tabIndex = "1" })
                        @*<input type="email" class="form-control" placeholder="Email Address" id="txtForgotPasswordEmail" name="txtForgotPasswordEmail" required tabindex="1">*@
                    </div>

                    <div class="form-group">
                        <div class="btn-group-justified">
                            <input type="submit"  class="btn btn-lg btn-green full-width" value="Send Reset Link" tabindex="2">
                        </div>
                    </div>
                    @*</form>*@
                }
            </div>
        </div>
    </div>
</div> <!-- End Forgot Password Modal -->

LYSApp/LYSApp.Web/Views/Shared/_Header.cshtml
@using LYSApp.Web.Services;
<div class="home-header">
    <a href="@Url.Action("Index","Account")"><div class="home-logo osLight"><span class="fa fa-home"></span>lockyourstay</div></a>
    @if (SessionManager.GetSessionUser() == null)
    {
        <a  class="home-navHandler visible-xs"><span class="fa fa-bars"></span></a>
        <div class="home-nav">
            <ul>
                <li><a  data-toggle="modal" data-target="#signup">Sign Up</a></li>
                <li><a data-toggle="modal" data-target="#signin">Sign In</a></li>
                <li><a class="btn btn-dark-brown" data-target="#modal-list-your-property" data-toggle="modal">List a Property</a></li>
            </ul>
        </div>
    }
    else
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            var user=SessionManager.GetSessionUser();
            string name = String.Empty;
            if (user.FirstName != null && user.FirstName != String.Empty)
            {
                name = user.FirstName + " " + user.LastName;
            }
            else
            {
                if (user.LastName != null && user.LastName != String.Empty)
                {
                    name = user.LastName;
                }
                else
                {
                    name = "Guest";
                }
            }
           
            @Html.AntiForgeryToken()
            <div class="headerUserWraper">
                <a  class="userHandler dropdown-toggle" data-toggle="dropdown"><span class="icon-user"></span></a>
                <a  class="headerUser dropdown-toggle" data-toggle="dropdown">
                    <img class="avatar headerAvatar pull-left" id="hdrProfilePicture" src='@Url.Content(user.ProfilePicture != null && user.ProfilePicture != String.Empty ? user.ProfilePicture : "~/Images/default_profile_pic.jpg")' alt="avatar">
                    <div class="userTop pull-left">
                        <span class="headerUserName">@name</span> <span class="fa fa-angle-down"></span>
                    </div>
                    <div class="clearfix"></div>
                </a>
                <div class="dropdown-menu pull-right userMenu" role="menu">
                    <div class="mobAvatar">
                        <img class="avatar mobAvatarImg" src='@Url.Content("~/images/avatar-1.png")' alt="avatar">
                        <div class="mobAvatarName">@name</div>
                    </div>
                    <ul>
                        <li><a href='@Url.Action("ViewProfile","User")'><span class="icon-user"></span>Profile</a></li>
                        <li><a href='@Url.Action("PropertyDetails", "Search")'><span class="icon-user"></span>Property Details</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()"><span class="icon-power"></span>LogOff</a></li>
                    </ul>
                </div>
            </div>
        }
    }

</div>

LYSApp/LYSApp.Web/Views/Shared/_Layout.cshtml
@*@using LYSApp.Model;
@model LYSApp.Model.AccountViewModel
@{
    //if error in log in
    string loginError = String.Empty; 
    if (Model != null && Model.LoginViewModel != null && Model.LoginViewModel.LoginError != null && Model.LoginViewModel.LoginError != String.Empty)
    {
        loginError = Model.LoginViewModel.LoginError;
    }
    //if error in  signup
    string registerError = String.Empty;
    if (Model != null && Model.RegisterViewModel != null && Model.RegisterViewModel.RegisterError != null && Model.RegisterViewModel.RegisterError != String.Empty)
    {
        registerError = Model.RegisterViewModel.RegisterError;
    }
    
}*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>LockYourStay | @ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    @Styles.Render("~/Content/layout")
    @*<link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/simple-line-icons.css" rel="stylesheet" />
    <link href="~/Content/fullscreen-slider.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/app.css" rel="stylesheet" />
    <link href="~/Content/lockyourstay.css" rel="stylesheet" />*@
   
    <link href="@Url.Content("~/favicon.ico")" rel="icon" />
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="notransition no-hidden">

    <!-- Header -->
    @Html.Partial("_Header")

    <!-- Content -->
    @RenderBody()

    <!-- Footer -->
    @Html.Partial("_Footer")
    @Html.Partial("_SignInModal",null,new ViewDataDictionary())
    @Html.Partial("_SignUpModal", null, new ViewDataDictionary())
    @Html.Partial("_EmailVerificationModal", null, new ViewDataDictionary())
    @Html.Partial("_ForgotPasswordModal", null, new ViewDataDictionary())
    @Html.Partial("_ListYourPropertyModal", null, new ViewDataDictionary())
    @Html.Partial("_MessageModal")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryuitouchpunch")
    @Scripts.Render("~/bundles/jqueryplaceholder")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquerytouchSwipe")
    <script src="http://maps.googleapis.com/maps/api/js?v=3;libraries=geometry&amp;libraries=places" type="text/javascript"></script>
    @Scripts.Render("~/bundles/infobox")
    @Scripts.Render("~/bundles/jqueryvisible")
    <script src='@Url.Content("~/Scripts/home.min.js")' type="text/javascript"></script>
    @Scripts.Render("~/bundles/validate")
    @Scripts.Render("~/bundles/unobtrusive-ajax")
    @Scripts.Render("~/bundles/lockyourstay")
    @Html.Partial("_Show_And_Hide_Progress")
    @if (System.Configuration.ConfigurationManager.AppSettings.Get("EnvironmentName") == "Production")
    {
        <!-- Google Analytics code -->
        @Scripts.Render("~/bundles/lockyourstayGA")
    }
    <script>
    var EmailSubscribeURL = '@Url.Action("EmailSubscribe","Account")';
    var ForgotPasswordURL = '@Url.Action("ForgotPassword", "Account")';
    var ListYourPropertyURL = '@Url.RouteUrl(LYSApp.Web.Services.Common.RouteNames.ListYourPropertyPost)';
    @*var loginError = '@loginError'
    var registerError = '@registerError'*@
    </script>
      
    @Scripts.Render("~/bundles/layout")
    
    <!--custom scripts for childs-->
    @RenderSection("scripts", false);
</body>
</html>

LYSApp/LYSApp.Web/Views/Shared/_MessageModal.cshtml
   <!-- Message Modal -->
<div class="modal fade in" id="modal-message" role="dialog" aria-labelledby="modal-messageLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modal-messageLabel">Message</h4>
                </div>*@
            <div class="modal-body">
                <div class="alert alert-success" style="font-size: 1.2em;margin-bottom: 0px;font-weight: 300;">
                    <i class="fa fa-comments-o"></i><span style="margin:0% 1% 0% 1%;" id="spnMessage" class="text-justify"></span><i data-dismiss="modal" class="fa fa-times pull-right"></i>
                </div>
            </div>
            @*<div class="modal-footer">
                    <input type="button" class="btn btn-green" data-dismiss="modal" value="Okey" />
                </div>*@
        </div>
    </div>
</div> <!-- End Message Modal -->

LYSApp/LYSApp.Web/Views/Shared/_SearchPartial.cshtml
@model LYSApp.Model.SearchViewModel


<div class="search-panel">
    @*<form class="form-inline" role="form">*@
    @using (Html.BeginForm("GetPGs", "Search", FormMethod.Post, new { role = "form", id = "form-Search-pg", @class = "form-inline" }))
    {
        <div class="form-group">
            <input type="text" class="form-control area"  id="txtArea" placeholder="Area" tabindex="1">   
           @Html.HiddenFor(model => model.AreaID)      
        </div>
        <div class="form-group hidden-xs adv">
            @Html.DropDownListFor(model => model.Gender, new List<SelectListItem>{
                        new SelectListItem{ Text="Male", Value="1"},
                        new SelectListItem{ Text="Female", Value="2"}
                        }, "Gender", new { @class = "form-control", maxlength = "50", placeholder = "Gender", tabIndex = "2" })
        </div>
        <div class="form-group hidden-xs adv">
            <div class='input-group'>
                <input type="text" name="BookingFromDate" class="form-control lys-date-picker" id='txtBookingFromDate' placeholder="Booking From" tabindex="3" readonly />
                @*@Html.TextBoxFor(model => model.BookingFromDate, new { @class = "form-control lys-date-picker", id = "txtBookingFromDate", placeholder = "Booking From", tabindex = "3", @readonly = "true", value = "" })*@
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
                      
        </div>
        <div class="form-group hidden-xs adv">            
            <div class='input-group'>
                <input type="text" name="BookingToDate" class="form-control lys-date-picker" id='txtBookingToDate' placeholder="Booking Upto" tabindex="4" readonly />
                @*@Html.TextBoxFor(model => model.BookingToDate, new {@class="form-control lys-date-picker" , id="txtBookingToDate", placeholder="Booking Upto" ,tabindex="4", @readonly="true",value=""  })*@
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>   
            <div id="divSelectFromDateWarning" style="display:none">Please select From date</div>    
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-green" id="btnSearchHome" value="Search" tabindex="5" />
            <a class="btn btn-o btn-white pull-right visible-xs" id="advanced">Advanced Search <span class="fa fa-angle-up"></span></a>
        </div>
        @*</form>*@
    }
</div>